apiVersion: apps/v
kind: Deployment
metadata:
  name: gnc-deploy
  labels: gnc-site
spec:
  replicas: 3
  selector:
    matchLabels:
      name: gnc-site
  template:
    metadata: {labels: {app: gnc-site}}
    spec:
      containers:
      - name: gnc-site
        image: gcr.io/gamenightcrewicu/gnc-site:${TAG}
        command:
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: gnc-config
            mountPath: /etc/gnc/
            readOnly: true
      volumes:
        - name: gnc-config
          configMap: { name: gnc-config }
