apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gnc-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gnc-site
    spec:
      containers:
      - name: gnc-site
        image: gcr.io/gamenightcrewicu/gnc-site:${TAG}
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: gnc-config
            mountPath: /etc/gnc/
            readOnly: true
      volumes:
        - name: gnc-config
          configMap: { name: gnc-config }
