apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamenightcrewicusite
  labels: {app: gamenightcrewicusite}
spec:
  replicas: 3
  template:
    metadata: {labels: {app: gamenightcrewicusite}}
    spec:
      containers:
      - name: gamenightcrewicusite
        image: gcr.io/gamenightcrewicu/gnc-site:${TAG}
        command:
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: gnc-config
            mountPath: /etc/gnc/
            readOnly: true
      volumes:
        - name: gnc-config
          configMap: { name: gnc-config }

kind: Service
apiVersion: v1
metadata:
  name: gamenightcrewicusite
spec:
  type: LoadBalancer
  selector:
    app: gamenightcrewicusite
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

